ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
-- ctrl + enter : 1line execute

CREATE USER kh_sh IDENTIFIED BY kh1234;
CREATE USER workbook IDENTIFIED BY workbook;
CREATE USER exam_sh IDENTIFIED BY 1234;
CREATE USER shopping_sh IDENTIFIED BY sh;
CREATE USER sh_sample IDENTIFIED BY sample;

GRANT RESOURCE, CONNECT TO kh_sh;
GRANT RESOURCE, CONNECT TO workbook;
GRANT RESOURCE, CONNECT TO exam_sh;
GRANT RESOURCE, CONNECT TO shopping_sh;
GRANT RESOURCE, CONNECT TO sh_sample;

GRANT CREATE SESSION TO sh_sample;

ALTER USER workbook DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
ALTER USER kh_sh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
ALTER USER exam_sh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
ALTER USER shopping_sh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
ALTER USER sh_sample DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CREATE VIEW TO kh_sh;

GRANT CREATE TABLE TO sh_sample;

GRANT SELECT ON kh_sh.EMPLOYEE TO sh_sample;
REVOKE SELECT ON kh_sh.EMPLOYEE FROM sh_sample;