ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE ;
-- ctrl + enter : 1line execute

CREATE USER kh_sh IDENTIFIED BY kh1234;
CREATE USER workbook IDENTIFIED BY workbook;

GRANT RESOURCE, CONNECT TO kh_sh;
GRANT RESOURCE, CONNECT TO workbook;

ALTER USER workbook DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
ALTER USER kh_sh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

