-- TCL (Transaction Control Language)

-- SAVEPOINT : not rollback all

SAVEPOINT "240306-16:32";

SELECT * FROM EMPLOYEE2;

SELECT * FROM DEPARTMENT2;

UPDATE DEPARTMENT2 SET DEPT_ID = 'D9' WHERE DEPT_ID = 'D0';

COMMIT;

INSERT INTO DEPARTMENT2 VALUES ('T1', '개발1팀'. 'L2');
INSERT INTO DEPARTMENT2 VALUES ('T2', '개발2팀'. 'L2');
INSERT INTO DEPARTMENT2 VALUES ('T3', '개발3팀'. 'L2');

