-- DDL (Data Definition Language)

CREATE TABLE DEPT_COPY AS SELECT * FROM DEPARTMENT;

ALTER TABLE DEPT_COPY ADD CONSTRAINT DEPT_TITLE_U UNIQUE(DEPT_TITLE);
ALTER TABLE DEPT_COPY DROP CONSTRAINT DEPT_TITLE_U;

ALTER TABLE DEPT_COPY ADD CONSTRAINT DEPT_TITLE_NN NOT NULL(DEPT_TITLE);
ALTER TABLE DEPT_COPY MODIFY DEPT_TITLE NOT NULL;
ALTER TABLE DEPT_COPY MODIFY DEPT_TITLE NULL;


ALTER TABLE DEPT_COPY ADD DEPT_STATUS VARCHAR2(10);
ALTER TABLE DEPT_COPY ADD CONSTRAINT CK_STATUS_2 CHECK(DEPT_STATUS IN ('Y', 'N'));

ALTER TABLE DEPT_COPY DROP COLUMN DEPT_STATUS;

SELECT * FROM DEPT_COPY;

INSERT INTO DEPT_COPY VALUES ('D10', '1개발1팀', 'L1');
INSERT INTO DEPT_COPY VALUES ('D11', '개발2팀', 'L1', DEFAULT);

ALTER TABLE DEPT_COPY MODIFY DEPT_ID VARCHAR2(3);
UPDATE DEPT_COPY SET DEPT_TITLE = '개발1팀' WHERE DEPT_ID = 'D10';

ALTER TABLE DEPT_COPY MODIFY DEPT_STATUS DEFAULT 'Y';
UPDATE DEPT_COPY SET DEPT_STATUS = DEFAULT;

COMMIT;

ALTER TABLE DEPT_COPY DROP COLUMN DEPT_STATUS;

DROP TABLE DEPT_COPY;

ROLLBACK;

CREATE TABLE DEPT_COPY AS SELECT * FROM DEPARTMENT;
ALTER TABLE DEPT_COPY ADD CONSTRAINT D_COPY_PK PRIMARY KEY(DEPT_ID);

ALTER TABLE DEPT_COPY RENAME COLUMN DEPT_TITLE TO DEPT_NAME;

SELECT * FROM DEPT_COPY;

ALTER TABLE DEPT_COPY RENAME CONSTRAINT D_COPY_PK TO DEPT_COPY_PK;

ALTER TABLE DEPT_COPY RENAME TO DCOPY;

SELECT * FROM DCOPY;

DROP TABLE DCOPY;

CREATE TABLE TB1 (
TB1_PK NUMBER PRIMARY KEY,
TB1_COL NUMBER
);

CREATE TABLE TB2 (
TB2_PK NUMBER PRIMARY KEY,
TB2_COL REFERENCES TB1
);

INSERT INTO TB1 VALUES (1, 100);
INSERT INTO TB1 VALUES (2, 200);
INSERT INTO TB1 VALUES (3, 300);
INSERT INTO TB1 VALUES (4, 400);

SELECT * FROM TB1;

COMMIT;

SELECT * FROM TB2;

INSERT INTO TB2 VALUES (11, 1);
INSERT INTO TB2 VALUES (12, 2);
INSERT INTO TB2 VALUES (13, 3);
INSERT INTO TB2 VALUES (14, 4);

COMMIT;

DROP TABLE TB1;

DROP TABLE TB1 CASCADE CONSTRAINTS;

SELECT * FROM TB2;

COMMIT;

INSERT INTO TB2 VALUES (15, 5);

ALTER TABLE TB2 RENAME COLUMN TB2_COL TO TB2_C;



