-- SEQUENCE

CREATE SEQUENCE SEQ_TEST;

SELECT SEQ_TEST.NEXTVAL FROM DUAL;

CREATE TABLE EMP_TEMP
AS SELECT EMP_ID, EMP_NAME FROM EMPLOYEE;

SELECT * FROM EMP_TEMP;

CREATE SEQUENCE SEQ_TEMP
START WITH 223
INCREMENT BY 10
NOCYCLE
NOCACHE;

INSERT INTO EMP_TEMP VALUES(SEQ_TEMP.NEXTVAL, '홍길동');
INSERT INTO EMP_TEMP VALUES(SEQ_TEMP.NEXTVAL, '김길동');
INSERT INTO EMP_TEMP VALUES(SEQ_TEMP.NEXTVAL, '전길동');

ALTER SEQUENCE SEQ_TEMP
INCREMENT BY 1;

INSERT INTO EMP_TEMP VALUES(SEQ_TEMP.NEXTVAL, '문길동');
INSERT INTO EMP_TEMP VALUES(SEQ_TEMP.NEXTVAL, '종길동');
INSERT INTO EMP_TEMP VALUES(SEQ_TEMP.NEXTVAL, '황길동');

DROP TABLE EMP_TEMP;
DROP VIEW V_DCOPY2;
DROP SEQUENCE SEQ_TEMP;
DROP SEQUENCE SEQ_TEST;

GRANT SELECT ON EMPLOYEE TO sh_sample;