-- INDEX

CREATE TABLE EMP_CO AS SELECT * FROM EMPLOYEE;


CREATE INDEX IND ON EMP_CO (EMP_ID);

-- Primary key / Unique [constraints] default = Index

CREATE TABLE TB_IDX_TEST (
TEST_NO NUMBER PRIMARY KEY,
TEST_ID VARCHAR2(20) NOT NULL
);

BEGIN 
	FOR I IN 1..1000000
	LOOP 
		INSERT INTO TB_IDX_TEST VALUES (I, I||' TEST');
	END LOOP;
END;


SELECT * FROM TB_IDX_TEST WHERE TEST_ID = '500000 TEST';

SELECT * FROM TB_IDX_TEST WHERE TEST_NO = 500000;

SELECT * FROM EMPLOYEE;